# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6e82dfaf59707efeb3a3fbbde9d09d6e1fab304672bae7ac96a785cd64be31291af5df66a2dc026d7674b438fd678300f3829342feb7d9648cc1936b822e46

test:
  secret_key_base: 19bb0d94160052948e4ed7d44af96970f8901e6530f6948513cec28570a8cdecb14c6e79b897d3c434a91d9df9be2d6c5410311bf0dd340a4ccf739ae3af7861

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
